version: "3"
services:
  postgres:
    image: postgres:alpine
    restart: always
    hostname: localpostgres
    environment:
      POSTGRES_DB: learn_type_orm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 54321:5432
    networks:
      - network
#    volumes:
#      - /data/postgresql:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    restart: always
    hostname: localredis
    ports:
      - 63790:6379
    command:
      - redis-server
#    volumes:
#      - ./data:/data
    networks:
      - network
  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: localrabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=rabbit
    networks:
      - network
#    volumes:
#      - ./data:/var/lib/rabbitmq
  node:
    image: learn_koa
    restart: always
    stdin_open: true
    hostname: localnode
    tty: true
    environment:
      APP_ENV: dev
      PORT: 3000
      DATABASE_CONNECT: postgresql://postgres:postgres@localpostgres:54321/learn_type_orm
      RABBIT_MQ_STATUS: 0
      RABBIT_MQ_HOST: localrabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_PASS: rabbit
      RABBIT_MQ_USER: root
      REDIS_STATUS: 0
      REDIS_HOST: localredis
      REDIS_PORT: 63790
      REDIS_DB: 1
      MAILER_DSN: smtp://1424033781@qq.com:mtmjjvwcwyahijjd@smtp.qq.com
      FROM_EMAIL: 1424033781@qq.com
      DEV_EMAIL: qq52577517@163.com
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - network
networks:
  network: {}
