version: "3"
services:
  postgres:
    image: postgres:alpine
    restart: always
    hostname: localpostgres
    environment:
      POSTGRES_DB: learn_type_orm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 54321:5432
    networks:
      - network
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    restart: always
    hostname: localredis
    ports:
      - 63790:6379
    command:
      - redis-server
    volumes:
      - ./docker/redis:/data
    networks:
      - network
  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: localrabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=rabbit
    networks:
      - network
    volumes:
      - ./docker/rabbitmq:/var/lib/rabbitmq
  node:
    image: learn_koa
    restart: always
    stdin_open: true
    hostname: localnode
    tty: true
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - network
networks:
  network: {}
